### ISSUE TITLE
Compatibilidade versao 4.0

### ISSUE THREAD

**Issue by wubuyun** [shpsyte/Correios#1]
ola, pretende lança a versao Mundi (leve internaciona, ems) do correios para entrega exterior ?

**Comment by shpsyte** [comment]
Ola, não tinha pensado nisso, vou dar uma olhada sobre o assunto e posto aqui os resultados, ok?
Tks,

**Comment by wubuyun** [comment]
amigo, vai sai nova versao? nop ja esta no versao 4.2

**Comment by shpsyte** [comment]
Cara, estou em uma correria não consigo dar atenção la no plugin... Mas estou me programando para fazê-lo

**Comment by wubuyun** [comment]
e o plugins do pagamento tbm vai atualizar meu chefe ?

**Comment by shpsyte** [comment]
Pretendo sim...

**Comment by marcelowu** [comment]
to na fila de espera tbm..

**Comment by marcelowu** [comment]
paypal express do nopcommerce 4.2 nao funciona, pelo menos no ubuntu nao.
